name: Playwright Tests
on:
  schedule:
    - cron: '1 0 * * *'
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Ensure browsers are installed
      run: python -m playwright install --with-deps
    - name: Run your tests with github report
      run: pytest --tracing=retain-on-failure --github-report
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-traces
        path: test-results/
